export const FIELD_DESCRIPTIONS = {
  1:  "Indicar Nombre o Nombres de la Persona Encuestada.",
  2:  "Indicar los Apellidos de la Persona Encuestada.",
  3:  "Colocar RUT sin puntos y CON guión. Ej: 12345647-8",
  4:  "Nueve dígitos. Ej: 998832810",
  5:  "Ejemplo: correo@mimail.com",
  6:  "Indicar nombre de la región, no el número. Se despliega una lista.",
  7:  "Indicar comuna donde está el negocio del Usuario.",
  8:  "Indicar área de atención o centro de Responsabilidad.",
  9:  "Indicar dirección donde habita el usuario.",
  10: "Indicar dirección donde está el predio. Se pueden colocar también coordenadas.",
  11: "Formato DD/MM/AAAA",
  12: "Hombre / Mujer / No responde / No aplica",
  13: "Pueblo originario del cual el usuario forma parte o se identifica. Ej: Mapuche, Aymará.",
  14: "Nivel que llegó el usuario: Ed. Básica / Media / Técnico / Universitaria",
  15: "Nombre de la Empresa de Alianza.",
  16: "Señalar el Rubro o Negocio que el Usuario comercializa al Poder Comprador. Ej: Frambuesa, Leche, Miel.",
  17: "Nombre que identifica la unidad operativa según Poder Comprador. Ej: UO Berries Longaví.",
  18: "Indicar si el usuario está en SAT / PRODESAL / PDTI / PADIS / PRODEMU",
  19: "Fecha en que se realiza la encuesta. Formato DD/MM/AAAA",
  20: "Indicar el número correspondiente al listado realizado previo al proceso de encuestar.",
  21: "S: Sí posee Iniciación de Actividades.\nN: No posee iniciación.",
  22: "Indicar si tiene renta Presunta o Efectiva.",
  23: "S: Productor actualmente puede comercializar al poder comprador.\nN: Productor no puede comercializar en estos momentos, ya sea porque no cumple los estándares requeridos o faltan aspectos legales o comerciales.",
  24: "Aquel que comercializa o lo hará a través de la Alianza. Ej: Frambuesa, Miel, Ovinos.",
  25: "Variedad de la especie principal. Ej: Dolomia.",
  26: "Definir un rango de venta de cosecha o venta del producto principal. Ej: Febrero-Abril. O en leche: Todo el año.",
  27: "Indicar si es Convencional, Orgánico, Producción Integral, Biodinámico, Natural, según el rubro involucrado.",
  28: "Indicar si posee certificación, cuál o cuáles: Global GAP, US GAP, Orgánico, etc.",
  29: "Indicar la cantidad total de há destinadas al negocio de alianza, o total de animales en inventario o total de colmenas. Año 2023 o temporada 2023/2024.",
  30: "Igual que campo 29 pero para Año 2024 o temporada 2024/2025.",
  31: "Cantidad total producida durante el año 2023 o Temporada 2023/2024, expresada en la unidad usada para el rubro (KG, LT, N° colmenas, etc.).",
  32: "Cantidad total producida durante el año 2024 o Temporada 2024/2025.",
  33: "Cantidad Vendida por el usuario al Poder Comprador durante el año 2023 o Temporada 2023-2024.",
  34: "Cantidad Vendida por el usuario al Poder Comprador durante el año 2024 o Temporada 2024-2025.",
  35: "Indicar cuál es la unidad usada en las cantidades. KG, LT, N° animales, N° de servicios, N° de Ton Métricas limpias, etc. Debe ser común a todos los usuarios de la alianza.",
  36: "Unidad para año 2024 (ver campo 35).",
  37: "Valor total de Ventas al Poder Comprador, expresado en $ pesos chilenos, año 2023 o Temporada 2023/2024.",
  38: "Valor total de Ventas al Poder Comprador, expresado en $ pesos chilenos, año 2024 o Temporada 2024/2025.",
  39: "Cuál es la especie o Producto de segunda importancia en el negocio del productor.",
  40: "Variedad/Raza de la especie secundaria (ver campo 25, aplicable a especie secundaria).",
  41: "Época de cosecha/producto para venta de especie secundaria (ver campo 26).",
  42: "Tipo de manejo de especie secundaria (ver campo 27).",
  43: "Certificación de especie secundaria (ver campo 28).",
  44: "Superficie/Inventario/Colmenas de especie secundaria, año 2023 (ver campo 29).",
  45: "Superficie/Inventario/Colmenas de especie secundaria, año 2024 (ver campo 30).",
  46: "Cantidad Producida especie secundaria, año 2023 (ver campo 31).",
  47: "Cantidad Producida especie secundaria, año 2024 (ver campo 32).",
  48: "Cantidad Vendida al PC especie secundaria, año 2023 (ver campo 33).",
  49: "Cantidad Vendida al PC especie secundaria, año 2024 (ver campo 34).",
  50: "Unidad de especie secundaria (ver campo 35-36).",
  52: "Monto Vendido al PC especie secundaria, año 2023 (ver campo 37).",
  53: "Monto Vendido al PC especie secundaria, año 2024 (ver campo 38).",
  54: "Suma de especie principal y secundaria (superficie/colmenas), año 2023, solo si poseen misma unidad.",
  55: "Suma de especie principal y secundaria (superficie/colmenas), año 2024, solo si poseen misma unidad.",
  56: "Suma cantidad producida E1+E2, año 2023, solo si poseen misma unidad.",
  57: "Suma cantidad producida E1+E2, año 2024, solo si poseen misma unidad.",
  58: "Suma cantidad vendida al PC E1+E2, año 2023, solo si poseen misma unidad.",
  59: "Suma cantidad vendida al PC E1+E2, año 2024, solo si poseen misma unidad.",
  60: "Unidad total (ver campos 35-36, solo si es misma unidad).",
  62: "Suma de monto vendido al PC E1+E2, año 2023, solo si poseen misma unidad.",
  63: "Suma de monto vendido al PC E1+E2, año 2024, solo si poseen misma unidad.",
  64: "Todos los ingresos directos que provienen de la comercialización del rubro principal y secundario.",
  65: "Suma de costos directos del rubro principal y secundario.",
  66: "Ingresos totales menos costos de producción explotación.",
  67: "Breve descripción de los 3 principales estándares del poder comprador que condicionan la compra del producto o permiten un mejor precio. Ej: 1. %IQF sobre 80%. 2. Cumplimiento pauta BPA sobre 70 pts.",
  68: "Estándar 2 (ver campo 67).",
  69: "Estándar 3 (ver campo 67).",
  70: "Si el estándar descrito es de inocuidad, calidad, productividad o comercial.",
  71: "Tipo del estándar 2 (ver campo 70).",
  72: "Tipo del estándar 3 (ver campo 70).",
  73: "S: Cumple con el estándar descrito.\nN: No cumple con el estándar descrito.",
  74: "Cumplimiento del estándar 2 (ver campo 73).",
  75: "Cumplimiento del estándar 3 (ver campo 73).",
  76: "Definir Nivel ALTO / MEDIO / BAJO del Productor, según visión del Poder Comprador.",
  77: "Definir Nivel ALTO / MEDIO / BAJO del Productor en el aspecto productivo.",
  78: "Definir Nivel ALTO / MEDIO / BAJO del Productor en calidad e inocuidad.",
  79: "Definir máximo 5 puntos críticos que posee el negocio del productor. Ej: Bajos rendimientos, Mala calidad de materia prima, Falta infraestructura, Sin apoyo contable.",
  80: "Punto crítico 2 (ver campo 79).",
  81: "Punto crítico 3 (ver campo 79).",
  82: "Punto crítico 4 (ver campo 79).",
  83: "Punto crítico 5 (ver campo 79).",
  84: "Clasificación del punto crítico: Productividad / Calidad / Inocuidad / Acceso al Mercado.",
  85: "Tipo del punto crítico 2 (ver campo 84).",
  86: "Tipo del punto crítico 3 (ver campo 84).",
  87: "Tipo del punto crítico 4 (ver campo 84).",
  88: "Tipo del punto crítico 5 (ver campo 84).",
  89: "Solución propuesta por el Poder Comprador que ayudará a definir qué tipo de apoyo debe recibir el productor (asesoría técnica, inversión, crédito, etc.).",
  90: "Propuesta de solución punto crítico 2 (ver campo 89).",
  91: "Propuesta de solución punto crítico 3 (ver campo 89).",
  92: "Propuesta de solución punto crítico 4 (ver campo 89).",
  93: "Propuesta de solución punto crítico 5 (ver campo 89).",
  94: "Indicar si requiere inversión: SI-Infraestructura / SI-Equipamiento / SI-Insumo / NO. No es vinculante, solo detectar la necesidad para que el Poder Comprador realice el Plan de Inversión.",
  95: "¿Requiere inversión? PC 2 (ver campo 94).",
  96: "¿Requiere inversión? PC 3 (ver campo 94).",
  97: "¿Requiere inversión? PC 4 (ver campo 94).",
  98: "¿Requiere inversión? PC 5 (ver campo 94).",
  99: "En la celda colocar el número de la opción correspondiente (colocar 0 si fue encuestado):\n1. No entrega o contesta información.\n2. No estuvo ubicable.\n3. No posee información.\n4. Usuario renunció al programa.\n5. Otro (detallar en Notas).",
  100: "Colocar notas que a juicio del encuestador sea relevante mencionar.",
}

export const REGIONES_CHILE = [
  "Arica y Parinacota","Tarapacá","Antofagasta","Atacama","Coquimbo",
  "Valparaíso","Metropolitana","O'Higgins","Maule","Ñuble","Biobío",
  "Araucanía","Los Ríos","Los Lagos","Aysén","Magallanes",
]

export const TIPOS_PC = ["Productividad","Calidad","Inocuidad","Acceso al Mercado"]
export const NIVELES = ["ALTO","MEDIO","BAJO"]
export const TIPOS_ESTANDAR = ["Productividad","Calidad","Inocuidad","Comercial"]
export const PROGRAMAS_INDAP = ["SAT","PRODESAL","PDTI","PADIS","PRODEMU","Otro"]
